# .terraform-docs.yml
content: |-
  # Windows Server Vagrant boxes

  Build and deploy Windows Vagrant boxes with Hashicorp Packer.

  ## Version
  | Windows Server         | Tag |
  | ---------------------- | ----- |
  | Windows Server 2022 Standard Core | 2022-sc |
  | Windows Server 2022 Standard Core + Active-Directory | 2022-sc-ad |

  ## Prerequisites
  To upload to Vagrant Cloud, define the environment variable 'VAGRANT_CLOUD_TOKEN'.

  ## Usage
  To deploy all tags run the following commands:

  ```bash
  make packer-init
  make packer-validate
  make packer-build
  ```

  {{ .Inputs }}

  ## Release
  To release a new version use the release-please bot.
  Afterwards pull the main branch and run the packer build (see 'Usage').

  ## Inspirations
    - https://github.com/ruzickap/packer-templates
    - https://github.com/eaksel/packer-Win2019
    - https://github.com/gusztavvargadr/
